title: ReLuna
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://reluna-dd.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Über uns
    url: /about
  - title: Kontakt
    url: /contact

social:
  github: urbansand
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
